### ISSUE TITLE
socket bind error: Permission denied

### ISSUE THREAD

**Issue by Amalkh5** [iizukanao/node-rtsp-rtmp-server#100]
Hi  , 
I tried to stream a video using vlc on the server but I got this error 

﻿-- logger module started --
lua: Lua HTTP interface
core error: socket bind error: Permission denied
core error: socket bind error: Permission denied
core error: cannot create socket(s) for HTTP host
lua error: Error loading script /usr/lib/vlc/lua/intf/http.luac: lua/intf/http.lua:336: Failed to create HTTP host
-- logger module stopped --

**Comment by iizukanao** [comment]
@Amalkh5 I think you have to run your program as root with `sudo`.

**Comment by Amalkh5** [comment]
@iizukanao I did but still same problem

**Comment by iizukanao** [comment]
@Amalkh5 "Permission denied" is outside the scope of this program. Maybe you don't have enough permission to run it on your machine.

**Comment by Amalkh5** [comment]
@iizukanao tried with root permission but it's maybe vlc problem ,Thanks
