### ISSUE TITLE
mp4.coffee:915:16: error: unexpected newline

### ISSUE THREAD

**Issue by Porske** [iizukanao/node-rtsp-rtmp-server#103]
hi,
when I lauch the command `sudo coffee server.coffee` i get this error
`/home/pi/node-rtsp-rtmp-server/mp4.coffee:915:16: error: unexpected newline
    obj = super
               ^
`
node v8.9.1
and `coffee-script` v1 is installed
what am I doing wrong?

**Comment by iizukanao** [comment]
@Porske I think you have installed CoffeeScript v2. Check your CoffeeScript version with `coffee -v`. To install CoffeeScript v1, you have to install `coffee-script` npm package instead of `coffeescript`.

**Comment by Porske** [comment]
thank you for your super fast reply, yes I have installed coffee v2 damn!
I have try to uninstall, but without success :sob: 
`pi@raspberrypi:~ $ sudo npm uninstall coffee`
`up to date in 0.578s`
`pi@raspberrypi:~ $ sudo npm uninstall coffeescript -g`
`up to date in 0.82s`
`pi@raspberrypi:~ $ coffee -v`
`CoffeeScript version 2.0.2`

**Comment by Porske** [comment]
EDIT:
I remove all reference to coffee with `locate coffee` and install coffe v1 correctly
`pi@raspberrypi:~/node-rtsp-rtmp-server $ coffee -v`
`CoffeeScript version 1.12.7` 💪

seem to work
`pi@raspberrypi:~/node-rtsp-rtmp-server $ ./start_server.sh `
`2017-11-21 10:01:20.173 attachRecordedDir: dir=file app=file`
`2017-11-21 10:01:20.290 [rtsp/http] server error: listen EADDRINUSE 0.0.0.0:80`
`2017-11-21 10:02:51.993 [custom_receiver] new connection to VideoData`
`2017-11-21 10:02:52.003 [custom_receiver] new connection to VideoControl`
`2017-11-21 10:02:52.008 [custom_receiver] new connection to AudioData`
`2017-11-21 10:02:52.011 [custom_receiver] new connection to AudioControl`
`2017-11-21 10:02:52.047 [custom_receiver] connection to AudioControl closed`
`2017-11-21 10:02:52.049 [custom_receiver] connection to AudioData closed`
`2017-11-21 10:02:52.051 [custom_receiver] connection to VideoData closed`
`2017-11-21 10:02:52.052 [custom_receiver] connection to VideoControl closed`
`2017-11-21 10:03:08.279 [custom_receiver] new connection to VideoData`
`2017-11-21 10:03:08.282 [custom_receiver] new connection to VideoControl`
`2017-11-21 10:03:08.285 [custom_receiver] new connection to AudioData`

`pi@raspberrypi:~/picam $ ./picam --alsadev hw:1,0 --rtspout`
`configuring devices`
`capturing started`

now how can I get the rtsp:// output link?
Thanks for your help!!!

**Comment by iizukanao** [comment]
@Porske You did it! Great!

**Comment by Porske** [comment]
thank you again!!! :muscle:
