### ISSUE TITLE
Multiple Stream and login system

### ISSUE THREAD

**Issue by cengizakcan** [iizukanao/node-rtsp-rtmp-server#114]
Hello,
Firstly thank you for this share. Everything very much good but i have a problem.
can you help me?
i want to make a multi stream live cast with login system. 

your repo is only one allow stream. 

i waiting your answer

**Comment by iizukanao** [comment]
@cengizakcan This server supports multiple streams. You can publish any number of streams simultaneously. You have to build login system yourself.

**Comment by pelcom** [comment]
Hello,
@iizukanao I really appreciate the great work done here. I would like to ask a couple of question about this module.
Firstly, can RTMP and RTSP allow cookie based authentication such that i can extend my existing express app authentication to this?
Also, if cookie based authentication is not possible can you suggest the best authen
tication method i can use. 

Thanks

**Comment by iizukanao** [comment]
@pelcom Cookie based authentication is not supported out of the box, but you can modify the source code to be able to do that. Alternatively, you can do URL based authentication by modifying `setLivePathConsumer` in server.coffee. Please open new issue if you need further assistance.
