### ISSUE TITLE
"Waiting for keyframe"

### ISSUE THREAD

**Issue by Alinaki** [iizukanao/node-rtsp-rtmp-server#12]
Hi! It all works when trying to stream mp4 video, but when I try to encode other videos to mp4 — I got this:
2015-03-18 01:50:00.759 [rtmp] waiting for the key frame for client 9x3LDXUc
and it only works only when I connect exact at the beginning of stream.

The only solution is to use -g 1 option. But it seems to be very strange, because parameter for g need to be at least fps*2, not every frame!

ffmpeg -re -i video.avi -vcodec libx264 -g 1 -acodec libvo_aacenc -ar 44100 -ac 2 -f flv rtmp://localhost/live/myStream

Is it my mistake?

**Comment by iizukanao** [comment]
The time between "waiting for keyframe" and "started streaming" depends on the keyframe interval of source video. In general, keyframe interval should be less than 3 seconds for live streaming.

If your video is 30 fps, `-g 60` limits the maximum distance between keyframes to 2 seconds (60 frames). In this case you'll see "started streaming" message within two seconds after "waiting for keyframe" message. The default value of `-g` is 250.

Also, I've added a new config parameter to control this behavior. If you do not want to wait for a keyframe and start streaming immediately, edit config.coffee and set `rtmpWaitForKeyFrame` to `false`.

**Comment by iizukanao** [comment]
Please reopen the issue if you still have a problem.
