### ISSUE TITLE
Default streamName for an RTSP server

### ISSUE THREAD

**Issue by mhaddy** [iizukanao/node-rtsp-rtmp-server#125]
I've started the server with coffee server.coffee and it says that the server is running, but I can't seem to figure out what the streamName is?

```
mhadpi@mhadMirror:~/node-rtsp-rtmp-server $ coffee server.coffee
2019-02-18 18:15:50.644 attachRecordedDir: dir=file app=file
(node:4135) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2019-02-18 18:15:50.868 [rtsp] server started on port 8082
```

**Comment by iizukanao** [comment]
There is no default stream name. You can do either [static file streaming](https://github.com/iizukanao/node-rtsp-rtmp-server#serving-mp4-files-as-recorded-streams) or [live streaming](https://github.com/iizukanao/node-rtsp-rtmp-server#publishing-live-streams).

**Comment by mhaddy** [comment]
Thank you, I've started up the server, installed ffmpeg and tried to publish a live stream but still not able to connect. ffmpeg responds with:
```
[rtsp @ 0x732230] CSeq 2 expected, 0 received.
[rtsp @ 0x732230] method DESCRIBE failed: 404 Not Found
rtsp://IP_ADDRESS:PORT/live: Server returned 404 Not Found
```
But I know it's hitting the server because I can see the following in the console:
```
2019-02-23 08:01:18.637 [rtsp:client=c7] connected
2019-02-23 08:01:18.651 [rtsp:client=c7] requested stream not found: live
2019-02-23 08:01:18.666 [rtsp:client=c7] disconnected
```
Here's the ffmpeg command that I issue:
```
ffmpeg -re -i rtsp://IP_ADDRESS:PORT/live -c:v libx264 -preset fast -c:a libfdk_aac -ab 128k -ar 44100 -f rtsp -rtsp_transport tcp rtsp://IP_ADDRESS:PORT/live/some_stream_name_i_made_up
```
Guidance would be appreciated!

Two additional questions:
1. Where can I find the logs?
2. After issuing coffee server.coffee, how I put this to the background so I use the console/close the window without the process exiting?

**Comment by iizukanao** [comment]
@mhaddy 
Your command tells ffmpeg to publish (relay) stream from rtsp://IP_ADDRESS:PORT/live to rtsp://IP_ADDRESS:PORT/live/some_stream_name_i_made_up. I think that's not what you wish to do. Replace rtsp://IP_ADDRESS:PORT/live with a source mp4 file or an external live stream URL.

> Where can I find the logs?

Log messages are printed to console. To output the log to a file, use `tee` command.

> After issuing coffee server.coffee, how I put this to the background so I use the console/close the window without the process exiting?

You can use [`forever`](https://www.npmjs.com/package/forever) command to run the server in the background.

**Comment by mhaddy** [comment]
Hi @iizukanao Thanks so much for the quick reply ... I am so very confused. I thought this WAS my live stream URL: rtsp://IP_ADDRESS:PORT/live. Ultimately what I'm trying to do is use your repo to create an RTSP live stream URL on my Pi Zero W, and then from a different Pi that's running [MotionEye](https://github.com/ccrisan/motioneye), connect to that stream and monitor it for motion.

Is this not possible?

**Comment by iizukanao** [comment]
@mhaddy Are you using [picam](https://github.com/iizukanao/picam) for capturing video from Raspberry Pi Camera Module?

**Comment by mhaddy** [comment]
@iizukanao No, not running picam - just following the steps I've outlined above.

I'm going to pause my efforts on getting this to work - thank you for your suggestions - I will come back at a later date as I'm currently exploring other options.
