### ISSUE TITLE
End of stream?

### ISSUE THREAD

**Issue by dejarno** [iizukanao/node-rtsp-rtmp-server#14]
Hi

When i'm streaming the server detects the end of a stream, but he doesn't send this to the clients who are watching. This is a problem for most programs, for example while capturing with OpenCV or FFmpeg the program will be waiting forever for the next frame.

Is this a feature or a bug?

Greetings
Jarno

**Comment by iizukanao** [comment]
Hi, thanks for reporting the issue!
It was not implemented but I've fixed that in the latest code. The server now sends an end of stream signal to the client so that ffmpeg stops. Could you confirm that it solves the problem for you?

**Comment by dejarno** [comment]
Yes, problem solved.
Thanks!
