### ISSUE TITLE
python connection

### ISSUE THREAD

**Issue by reo-min** [iizukanao/node-rtsp-rtmp-server#148]
I have a question about it. 

I want to connect with python like openCV.

Is there any solution of it?

I've already made the media server and connected with the android app. 

Thank you very much.

**Comment by iizukanao** [comment]
I think you might be able to use [`cv.VideoCapture("rtsp://SERVER_IP:80/live/STREAM_NAME")`](https://docs.opencv.org/3.4/d8/dfe/classcv_1_1VideoCapture.html#a949d90b766ba42a6a93fe23a67785951).
See this example: https://stackoverflow.com/a/25764342

**Comment by reo-min** [comment]
Is the server_ip media server ip??

**Comment by iizukanao** [comment]
Yes, the ip address of the machine which node-rtsp-rtmp-server is running on.

**Comment by reo-min** [comment]
Thanks

The media server prints that

 c2: session=65245494 addr=192.168.35.220 port=38960 type=publish-tcp
2020-10-25 14:02:13.073 [rtsp/http/rtmpt:client=c2] started uploading stream live/fly

then I made the python like that

import cv2
ip_cam = cv2.VideoCapture("rtsp://192.168.35.220:80/live/app")
while(ip_cam.isOpened()):  
    ret, image = ip_cam.read()
    cv2.imshow('video', image)

but it didn't work...

**Comment by reo-min** [comment]
Thank you very much!

it did work!

**Comment by iizukanao** [comment]
Great!
