### ISSUE TITLE
RTSP not working on VLC

### ISSUE THREAD

**Issue by AlexMarambio** [iizukanao/node-rtsp-rtmp-server#152]
When trying RTMP live, it does work, but on the other hand, RTSP lives doest'n. IDK if it is becausse of VLC but trying on ffplay doesnt give any better result.

**Comment by vEuphemiav** [comment]
谢谢，您的邮件已收到。

**Comment by AlexMarambio** [comment]
没问题，谢谢你.

**Comment by iizukanao** [comment]
What is the frame rate, width/height and bit rate of the video stream?

**Comment by AlexMarambio** [comment]
> What is the frame rate, width/height and bit rate of the video stream?

Not sure, it is a very short and low quality video. I finally try other solution so it doesn't really matter now, hope it was just me or something wrong i was doing. 
Thank for the response btw :)
