### ISSUE TITLE
use FFmpeg Publish Failed.

### ISSUE THREAD

**Issue by iamluodong** [iizukanao/node-rtsp-rtmp-server#20]
Error: [rtmp:publish] malformed audio data: AudioSpecificConfig is missing
  at RTMPSession.parseAudioMessage (e:\git\rtmpserver\rtmp.coffee:741:21)
  at e:\git\rtmpserver\rtmp.coffee:1889:28
  at RTMPSession.handleData (e:\git\rtmpserver\rtmp.coffee:1959:7)
  at Socket.<anonymous> (e:\git\rtmpserver\rtmp.coffee:1994:23)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)

The source is ts over http.

use FMS no problem

**Comment by iizukanao** [comment]
There is a bug in ffmpeg where it doesn't send correct header for audio stream when `-c:a copy` is used with a .ts file. Avoid using .ts with ffmpeg, or use a non-experimental encoder at runtime (e.g. `-c:a libfdk_aac`).

**Comment by iamluodong** [comment]
OK

**Comment by roysG** [comment]
I run:
sudo ffmpeg -re -i /root/xx.mp4 -c:v copy -c:a copy -f flv rtmp://127.0.0.1/live/STREAM_NAME

I get error:

[flv @ 0x1903220] Failed to update header with correct duration.
[flv @ 0x1903220] Failed to update header with correct filesize.

**Comment by roysG** [comment]
I also tried to run:

 ffmpeg -re -i /root/xx.mp4 -c:v libx264 -preset fast -c:a libfdk_aac -ab 128k -ar 44100 -f rtsp rtsp://localhost:80/live/STREAM_NAME

I got error:

Unknown encoder 'libfdk_aac'

**Comment by iizukanao** [comment]
@roysG Use ffmpeg that is built with libfdk_aac support. Alternatively, you can use [Native FFmpeg AAC Encoder](https://trac.ffmpeg.org/wiki/Encode/AAC#NativeFFmpegAACEncoder).

**Comment by iizukanao** [comment]
@roysG Please open new issue if you still have problems.
