### ISSUE TITLE
FFMpeg // RTM missed x packets

### ISSUE THREAD

**Issue by Dermiste** [iizukanao/node-rtsp-rtmp-server#22]
Hello there,

I am trying to make all that work. The server seems to work fine but when I feed a RTSP stream coming from my IP cam I seem to get a LOST of "RTM: missed x packets".
Here is a screenshot:
![screen shot 2015-07-01 at 12 02 32](https://cloud.githubusercontent.com/assets/1168706/8448844/6f08c7b2-1fe9-11e5-8b80-91ae5c5395e2.png)

Any idea what would cause this? I assume it is a ffmpeg issue and not a node.js issue ...
Thanks a lot !

**Comment by Dermiste** [comment]
Fixed by using -rtsp_transport tcp in the command right after ffmpeg -re:
ffmpeg -re -rtsp_transport tcp  -i input.mp4 -c:v copy -c:a copy -f flv rtmp://localhost/live/STREAM_NAME

**Comment by iizukanao** [comment]
You're right. Use TCP instead of UDP for reliable RTSP streaming from ffmpeg.
