### ISSUE TITLE
Codec // h264 in RTSP, but avc1 in RTMP

### ISSUE THREAD

**Issue by Dermiste** [iizukanao/node-rtsp-rtmp-server#23]
Hello,

I have been analysing the output of the RTMP stream, and it appears that the signature of the video codec is no longer h264, but acv1. I managed to see that through VLC in media informations.

Hence, when I try to play the RTMP stream in flash I get an error message:
[12:45:53.773] <<<< VTVideoDecoderSelection >>>> VTSelectAndCreateVideoDecoderInstanceInternal: no video decoder accepted for 'avc1'

And the framerate compared to the original stream is kind of shitty then ... about 10 fps in opposition of the 22fps provided by the live IP cam feed.

When I open both RTSP and RTMP stream in VLC everything is fine, so obviously the video codec used by the node app is not manageable by flash.

Any idea?

**Comment by iizukanao** [comment]
I don't understand what you wrote. Please describe your problem as follows.

- Steps to reproduce
- Actual results (the problem you are experiencing)
- Expected results
- Environment (OS, player software name and version)

**Comment by Dermiste** [comment]
Sorry about that.

In a nutshell, if I read the stream through the player I built using AS3/Flash I get this error and the video is very laggy:
[12:45:53.773] <<<< VTVideoDecoderSelection >>>> VTSelectAndCreateVideoDecoderInstanceInternal: no video decoder accepted for 'avc1'

If I play the stream using Strobe Media Playback or some online RTMP player everything is fine. So I went for that solution.

**Comment by iizukanao** [comment]
Sorry, I don't have experience in creating a video player in Flash, and have no idea about that error.
