### ISSUE TITLE
multiple streams are not supported

### ISSUE THREAD

**Issue by anton-nikolaev** [iizukanao/node-rtsp-rtmp-server#3]
Could you please explain why multiple streams are not supported? README said, that "you can push only one stream at a time". Does it mean, that we cant publish more than one RTMP live stream at a time? Thanks.

**Comment by EaterOfCode** [comment]
As this issue is already open for 8 months, is there being worked on this issue?

**Comment by zweigraf** [comment]
I know I am not working on this issue, but I would love to get this feature working. Maybe I can take another look at it.

**Comment by iizukanao** [comment]
@zweigraf I'll take it on. You don't need to work on this feature. It requires fair amount of work, since the codebase is really complicated.

**Comment by EaterOfCode** [comment]
When do you expect this to be done? if I may ask so

**Comment by iizukanao** [comment]
@EaterOfCode I can't say exact date, but I hope it will be done in the coming weeks.

**Comment by virtualfunction** [comment]
Also massively in favour of this... Keeping an eye on this as I'd like to move away from red5 (largely because my animosity towards Java)

**Comment by iizukanao** [comment]
Multi-stream support has landed on master.

**Comment by EaterOfCode** [comment]
Great job! Will look into creating an API this week hopefully then :)
