### ISSUE TITLE
communicating with the rtmp server

### ISSUE THREAD

**Issue by gokiburikin** [iizukanao/node-rtsp-rtmp-server#32]
i have a project written using MonaServer and i'd like to rewrite it in node.js using this rtmp module, but i'm not sure how to communicate with the rtmp server to do things like client authentication (using url parameters, which also don't seem to be supported in this project) and linking web clients to their corresponding rtmp client.

my assumption was i could just require the server in my node.js main file, but it's a synchronous call and the rtmp server just blocks the rest of the application from running, so i'm at a loss. if the functionality is already there, can you point me in the right direction?

**Comment by iizukanao** [comment]
You can implement your own authentication by modifying inside the block `streamServer.setLivePathConsumer  (uri, callback) ->` in [server.coffee, line 12](https://github.com/iizukanao/node-rtsp-rtmp-server/blob/master/server.coffee#L12). The basic idea is:

1. Issue a URL with unique token in your application.
2. Let the user access that URL.
3. Check if the requested URL contains a valid token (in server.coffee).

**Comment by gokiburikin** [comment]
oh okay, simple enough. thanks!
