### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by tasengin** [iizukanao/node-rtsp-rtmp-server#35]
Thank you for the great applications.
I was just wondering the easiest way to authenticate node-rtsp-rtmp-server.
Sincerely

**Comment by iizukanao** [comment]
In server.coffee, set `isAuthorized` to `true` or `false` based on requested URL (`pathname`).
https://github.com/iizukanao/node-rtsp-rtmp-server/blob/master/server.coffee#L12-L20

**Comment by tasengin** [comment]
Thank you. This is what I need :-)))
