### ISSUE TITLE
Does support HLS live streaming?

### ISSUE THREAD

**Issue by nvcken** [iizukanao/node-rtsp-rtmp-server#38]

**Comment by iizukanao** [comment]
No, it is not supported at this time. I'm planning to add this feature.

**Comment by nvcken** [comment]
Thanks, just for reference https://github.com/Jalle19/node-ffmpeg-mpegts-proxy (it is support HLS)
Hope it can help.
Anyway, does you know any hints to make iOS stream RTSP to node for publishing live stream ?

**Comment by iizukanao** [comment]
Thanks. Converting MPEG-TS into HLS is rather simple process, and ffmpeg can do that.

I don't know of iOS library, but I think someone must have already created an RTSP or RTMP library that you can use.

**Comment by nvcken** [comment]
Can't wait to see HLS support. Any roadmap.
Thanks so much.

**Comment by iizukanao** [comment]
I will do it in a few months.

**Comment by nvcken** [comment]
Thanks your great works

**Comment by arrowfunxtion** [comment]
Is it HLS supported now?

**Comment by iizukanao** [comment]
@arrowfunxtion Not yet. Sorry.
