### ISSUE TITLE
Hi, Does this error mean something?

### ISSUE THREAD

**Issue by kerneldeveloper** [iizukanao/node-rtsp-rtmp-server#42]
Hi,
Thanks for your hard work. This tool helps me a lot.
But when I use it relay rtsp stream , I encounter an error.
Although I encounter this error, I can watch video with VLC normally. So, I want to know if this error means something?
Thanks !
![1](https://cloud.githubusercontent.com/assets/8112645/14642080/af983aaa-067b-11e6-8a76-bd3d81c3fa64.png)

**Comment by iizukanao** [comment]
Hi, thanks for your message!
You don't have to worry about that error. It means client has gone away while server is still dealing with the client.

**Comment by kerneldeveloper** [comment]
Oh, I see. Thanks for the reply !
