### ISSUE TITLE
有中国的小伙伴关注这个项目吗？

### ISSUE THREAD

**Issue by cnyunguo** [iizukanao/node-rtsp-rtmp-server#53]
有中国的小伙伴关注这个项目吗？

**Comment by iizukanao** [comment]
Sorry, I can't read Chinese. What do you mean?

**Comment by falconyue** [comment]
his mean is is any chinese programmer watch this project ? it doesn't metter, it is time to close.

**Comment by iizukanao** [comment]
@falconyue Thanks! No such person involved in this project. Closing.
