### ISSUE TITLE
Socket error (c1): Error: read ECONNRESET

### ISSUE THREAD

**Issue by assilabel** [iizukanao/node-rtsp-rtmp-server#54]
hi !
can you please help me with this  Error: 

 Socket error (c1): Error: read ECONNRESET ?? thanks

**Comment by iizukanao** [comment]
In what situation are you getting that error? Basically, if you are not seeing any side effects, ECONNRESET is not harmful and you can ignore it.

**Comment by assilabel** [comment]
i think it's harmful,
i've changed the command in the server.coffee file by this one  

logger.setLevel logger.LEVEL_DEBUG

and when i run the server and test with this URL: rtmp://localhost/file/:mp4:video.mp4
that error appear on my console and it does not work !

**Comment by iizukanao** [comment]
The correct URL is rtmp://localhost/file/mp4:video.mp4
Also, please check if file/video.mp4 exists.

**Comment by assilabel** [comment]
sorry i made a mistake while typing the comment but i tested it correctly and i checked the video and it exists in /file

**Comment by assilabel** [comment]
by the way can you tell me how can i transfer an rtsp URL for live stream, to this server in order to get an rtmp format to this URL??

**Comment by iizukanao** [comment]
What client player are you using?

> by the way can you tell me how can i transfer an rtsp URL for live stream, to this server in order to get an rtmp format to this URL??

Yes, you can feed RTSP stream with ffmpeg:

    $ ffmpeg -i rtsp://EXTERNAL_STERAM_URL -c:a copy -c:v copy -f flv rtmp://localhost/live/test

Then, you can view the stream at rtmp://localhost/live/test

**Comment by assilabel** [comment]
i'm using VLC player

**Comment by iizukanao** [comment]
Use RTSP instead of RTMP. RTMP support in VLC is somewhat broken.
If you have to use RTMP, use Flash player instead.

**Comment by assilabel** [comment]
ok i'll try with flash player instead

now when i execute this command on my console 

$ ffmpeg -i rtsp://EXTERNAL_STERAM_URL -c:a copy -c:v copy -f flv rtmp://localhost/live/test

it appears: ffmpeg command unknown

**Comment by iizukanao** [comment]
Please install ffmpeg.

**Comment by assilabel** [comment]
i tried to but there is no version it responsed

**Comment by iizukanao** [comment]
Can you google "ffmpeg install <your OS name>"?

**Comment by assilabel** [comment]
ya already done i'll fix that thanks

**Comment by assilabel** [comment]
i used rtsp but it could not read the record also !

**Comment by iizukanao** [comment]
Can you be more specific? What command did you enter and what output did it produce?

**Comment by assilabel** [comment]
now i'm testing the rtsp server , i insert a video in the file folder and i'm trying to run it with my vlc

URL: rtsp://localhost:80/file/video.mp4 
the filename is video.mp4

and it still not running

**Comment by iizukanao** [comment]
Please post the full output of node-rtsp-rtmp-server.

**Comment by assilabel** [comment]
i used VLC just like you told me but it does not work and this error appear in my console:

2016-06-23 11:12:48.709 [rtmp:client=8G1L2aV4] connected
[rtmp: 1 sessions]
8G1L2aV4: addr=127.0.0.1 port=45845
2016-06-23 11:12:48.728 [rtmp:handshake] warning: unknown message format, assuming format 1
2016-06-23 11:12:48.747 [rtmp:receive] unknown (not implemented) AMF command: _checkbw
2016-06-23 11:12:48.751 [rtmp:client=8G1L2aV4] requested stream file/mp4:video.mp4
2016-06-23 11:12:48.751 error: failed to read file/video.mp4 or file/video.mp4.mp4: TypeError: Object # has no method 'accessSync'
2016-06-23 11:12:48.757 [rtmp:client=8G1L2aV4] error: stream not found: file/mp4:video.mp4
2016-06-23 11:12:48.771 [rtmp:client=8G1L2aV4] disconnected
[rtmp: 0 sessions]

i can't understand where the problem is! i put the video : video.mp4 in the file folder but it does not work !

**Comment by iizukanao** [comment]
What version of Node.js are you running? `node -v` will print the version.
Try installing latest Node.js from https://nodejs.org/

**Comment by assilabel** [comment]
when i insert my test external URL and execute this command on my console:

$ ffmpeg -i rtsp://EXTERNAL_STERAM_URL -c:a copy -c:v copy -f flv rtmp://localhost/live/test 

this ERROR appears:

`[tcp @ 0x2f96b60] Connection to tcp://localhost:1935 failed: Connection refused
[rtmp @ 0x2f71f80] Cannot open connection tcp://localhost:1935
rtmp://localhost/live/test: Connection refused
`

**Comment by iizukanao** [comment]
Start node-rtsp-rtmp-server first, then run ffmpeg.

**Comment by assilabel** [comment]
I've already run ffmpeg after starting the server

**Comment by iizukanao** [comment]
Something is wrong in your environment.
Are you running node-rtsp-rtmp-server and ffmpeg on the same machine?

**Comment by assilabel** [comment]
i reinstalled the server and started from the beginning, when i tried to to run it with the second method:

$ cd node-rtsp-rtmp-server
$ coffee -c .
$ sudo node server.js

when i enter : coffee -c , i get this promp in my terminal:

>coffee 

then when i enter sudo node server.js or even without sudo it prints wheather 

ReferenceError: sudo is not defined 
or
ReferenceError: node is not defined when i enter the command without sudo,

does that mean anything???

thanks!!

**Comment by assilabel** [comment]
well it's ok about this problem i forgot the full stop after coffee -c .

**Comment by assilabel** [comment]
now when i run my server and then execute this command:

>$ ffmpeg -i rtsp://EXTERNAL_STERAM_URL -c:a copy -c:v copy -f flv rtmp://localhost/live/test

it prints these errors on my console:

`[rtsp @ 0x20ced40] UDP timeout, retrying with TCP
[rtsp @ 0x20ced40] method PAUSE failed: 551 Option not supported
[rtsp @ 0x20ced40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Guessed Channel Layout for  Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://admin:acoba12345@192.168.1.112/h264/ch1/main':
  Metadata:
    title           : Media Presentation
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
2016-06-29 12:56:19.309 [rtmp:client=KhpmBBsf] connected
[rtmp: 1 sessions]
 KhpmBBsf: addr=127.0.0.1 port=60213
2016-06-29 12:56:19.418 [rtmp:receive] unknown (not implemented) AMF command: _checkbw
2016-06-29 12:56:19.458 [rtmp] publish: stream=live/test publishingType=live
[flv @ 0x2115fa0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Output #0, flv, to 'rtmp://localhost/live/test':
  Metadata:
    title           : Media Presentation
    encoder         : Lavf57.37.101
    Stream #0:0: Audio: pcm_alaw ([7][0][0][0] / 0x0007), 8000 Hz, mono, 64 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Press [q] to stop, [?] for help
[rtsp @ 0x20ced40] UDP timeout, retrying with TCP
[rtsp @ 0x20ced40] method PAUSE failed: 551 Option not supported
rtsp://admin:acoba12345@192.168.1.112/h264/ch1/main: Operation not permitted
[flv @ 0x2115fa0] Failed to update header with correct duration.
[flv @ 0x2115fa0] Failed to update header with correct filesize.
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
2016-06-29 12:56:29.548 [rtmp] FCUnpublish: test
2016-06-29 12:56:29.553 [rtmp:client=KhpmBBsf] socket error: Error: read ECONNRESET
2016-06-29 12:56:29.554 [rtmp:client=KhpmBBsf] disconnected
[rtmp: 0 sessions]
`

any help with this please?? thanks
