### ISSUE TITLE
error while trying to convert rtsp url into rtmp url through the server

### ISSUE THREAD

**Issue by assilabel** [iizukanao/node-rtsp-rtmp-server#55]
hi,
i ran the server and executed this command:
>ffmpeg -i rtsp://EXTERNEL_URL -c:a copy -c:v copy -f flv rtmp://localhost/live/test

and i got this problem:

`[rtsp @ 0x2832d40] UDP timeout, retrying with TCP

[rtsp @ 0x2832d40] method PAUSE failed: 551 Option not supported

[rtsp @ 0x2832d40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Guessed Channel Layout for  Input Stream #0.1 : mono `

Can you help me with this?? thanks

**Comment by iizukanao** [comment]
It seems there is something wrong with your source stream (EXTERNAL_URL). Can you run the ffmpeg with `-loglevel debug` option and post the full output?

**Comment by assilabel** [comment]
hi, i've resolved those problems.
Now this new error occurred:

>Guessed Channel Layout for Input Stream #0.1 : mono


>RTMP_Connect0, failed to connect socket. 111 (Connection refused)
>rtmp://localhost/live/test: Unknown error occurred

i tested the connection with my camera and it's pings right ok, i don't know what is the problem...
can you help me please??!! thanks
