### ISSUE TITLE
TypeError: Object #<Object> has no method 'accessSync'

### ISSUE THREAD

**Issue by assilabel** [iizukanao/node-rtsp-rtmp-server#58]
hi ,
i lunched my server and tried to read : video.mp4 from /file folder but this error appeared:

`error:failed to read file/video.mp4 or file/video.mp4.mp4: TypeError: Object #<Object> has no method 'accessSync'` 

any help please?? thanks

**Comment by jandrieu** [comment]
I ran into this also. In case it helps others, here's what worked.

First, I had the wrong node version and the npm install didn't report anything. Or at least, I didn't notice it. You'll want at least v0.12.0.

Second, after using NVM to change my node version, it took a while to realize that NVM installs to the $USER/.nvm directory and sets up environment variables accessible to that user. Running "sudo node server.js" switches the user to root and discards the env vars.  So, I was *still* running the rtsp-rtmp-server on the old node version.

The obvious result was that I kept getting errors from v0.10.40 after I updated with nvm twice: once to v4.8.0 and once to v0.12.0. Interesting bug/limitation with NVM. Maybe that note will help someone having similar problems.
