### ISSUE TITLE
Problem can help 

### ISSUE THREAD

**Issue by petrichbg** [iizukanao/node-rtsp-rtmp-server#67]
/usr/src/node-rtsp-rtmp-server-0.4.0# npm install -d
npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v7.2.0
npm info lifecycle node-rtsp-rtmp-server@0.4.0~preinstall: node-rtsp-rtmp-server@0.4.0
npm info linkStuff node-rtsp-rtmp-server@0.4.0
npm info lifecycle node-rtsp-rtmp-server@0.4.0~install: node-rtsp-rtmp-server@0.4.0
npm info lifecycle node-rtsp-rtmp-server@0.4.0~postinstall: node-rtsp-rtmp-server@0.4.0
npm info lifecycle node-rtsp-rtmp-server@0.4.0~prepublish: node-rtsp-rtmp-server@0.4.0
**npm WARN node-rtsp-rtmp-server@0.4.0 No repository field.**
npm info ok

no server.js 

coffee: command not found

**Comment by iizukanao** [comment]
Run `npm install -g coffee-script`

**Comment by petrichbg** [comment]
thank you i will test node-rtsp-rtmp-server ;)
