### ISSUE TITLE
how to receive the rtmp / rtsp stream and store them into the video on the server?

### ISSUE THREAD

**Issue by helxsz** [iizukanao/node-rtsp-rtmp-server#73]
Hi, @iizukanao , now I can run the server to receive the rtsp stream, how could I store them into the mp4 or other format like h.264 video file ?

**Comment by iizukanao** [comment]
@helxsz The server itself doesn't have such functionality, but you can do that with ffmpeg.
```
$ ffmpeg -i rtsp://server-ip:80/live/stream-name -c:v copy -c:a copy out.mp4
```

**Comment by helxsz** [comment]
Great Thanks, @iizukanao
