### ISSUE TITLE
How to broadcast RTSP Stream

### ISSUE THREAD

**Issue by khatrijatin** [iizukanao/node-rtsp-rtmp-server#75]
Is it possible to Broadcast RTSP Stream in any way ?

**Comment by iizukanao** [comment]
Solved via email conversation.

**Comment by khatrijatin** [comment]
is there any way to re-stream the same stream as broadcast ?

**Comment by iizukanao** [comment]
@khatrijatin You can receive the stream with ffmpeg (`ffmpeg -i
rtsp://RASPI_IP:80/live/picam`) and upload it to Ustream or YouTube.

**Comment by khatrijatin** [comment]
I don't want to upload it to ustream or youtube ... I want to broadcast it on my local network of 15 computers and laptops ?
what will be the full command 

ffmpeg -i rtsp://RASPI_IP:80/live/picam  ( then what to broadcast the stream ) 

I mean to say how to broadcast using ffmpeg ( -i is to input stream ... then how to get broadcast of it ) ?

**Comment by iizukanao** [comment]
@khatrijatin Why don't you just connect to the server over RTSP from each client?
