### ISSUE TITLE
nginx-rtmp-module

### ISSUE THREAD

**Issue by zhouxianjun** [iizukanao/node-rtsp-rtmp-server#76]
What's the difference with 'nginx-rtmp-module'

**Comment by iizukanao** [comment]
This is not an nginx's module.

**Comment by zhouxianjun** [comment]
I see, i just want to know the difference between this and nginx-rtmp-module -_-.

**Comment by iizukanao** [comment]
There are many differences and I can't tell you them briefly. See [README](https://github.com/iizukanao/node-rtsp-rtmp-server/blob/master/README.md) for the features.

**Comment by zhouxianjun** [comment]
ok.thanks!
