### ISSUE TITLE
How to set the quality of play?

### ISSUE THREAD

**Issue by zhouxianjun** [iizukanao/node-rtsp-rtmp-server#77]
I would like to ask how to set the quality of play?

**Comment by notedit** [comment]
quality of play  has  nothing to do this.

**Comment by zhouxianjun** [comment]
Is it possible to output according to different quality?

**Comment by iizukanao** [comment]
@zhouxianjun This server doesn't have such functionality built-in. You have to upload multiple streams with different qualities to the server.

**Comment by zhouxianjun** [comment]
okay. thanks
