### ISSUE TITLE
Can I convert RTSP to RTMP?

### ISSUE THREAD

**Issue by J-F-Liu** [iizukanao/node-rtsp-rtmp-server#8]
Can I receive RTSP stream from another server and serve as RTMP?

**Comment by iizukanao** [comment]
Unfortunately, no at this time.

**Comment by iizukanao** [comment]
I've added a feature to publish streams via RTSP. Please see https://github.com/iizukanao/node-rtsp-rtmp-server#from-rtsp-client for an example.
