### ISSUE TITLE
node-rtsp-rtmp-server coffee-script converted to es6 javascript source

### ISSUE THREAD

**Issue by tosscaster** [iizukanao/node-rtsp-rtmp-server#83]
https://github.com/tosscaster/node-rtsp-rtmp-server

I convert your node-rtsp-rtmp-server to es6 javascript source with decaffeinate and modify some.
mixin -> extends 

I start sever.js and find it works fine.
I will going to bug-fix and add functions. Thank for your work.
 
I hope it may be any help…

- https://github.com/decaffeinate/decaffeinate

**Comment by iizukanao** [comment]
@tosscaster Thank you for your great work! 🙂
