### ISSUE TITLE
Possible to stream subtitles or KLV metadata?

### ISSUE THREAD

**Issue by tayre** [iizukanao/node-rtsp-rtmp-server#88]
Is there a way I could send subtitles along with my live stream?

This:
`ffmpeg.exe -i rtsp://{live-feed} -i subtitle.srt -c:s copy -vcodec copy -an -f flv rtmp://localhost/live/myapp`
 
Currently produces `Subtitle codec 'subrip' for stream 1 is not compatible with FLV`

**Comment by iizukanao** [comment]
It appears that RTMP does not support subtitles.

**Comment by Enelar** [comment]
@iizukanao but RTMP support WebVTT and other metadata sending. That's for it was built for.
