### ISSUE TITLE
Close server [Question]

### ISSUE THREAD

**Issue by ozankonur** [iizukanao/node-rtsp-rtmp-server#96]
Okay, when I disconnect from putty, the server still running so when I try to connect the server I am getting error because server still running. So my question is how can I stop server, thank you.

**Comment by iizukanao** [comment]
@ozankonur Find the process ID of the server with `ps | grep node` command, then do `kill <process-id>`. Alternatively, you can do `killall node` to terminate the all Node.js processes.

**Comment by ozankonur** [comment]
Thank you
